apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy88
  labels:
    app: autodeploy88
  namespace: namespace-workflow-1705612948889
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy88
  template:
    metadata:
      labels:
        app: autodeploy88
    spec:
      containers:
        - name: autodeploy88
          image: acrworkflow1705612948889.azurecr.io/image-workflow-1705612948889:latest
          ports:
            - containerPort: 5000